---
- name: Test 'common' role
  gather_facts: no
  hosts: test
  become: yes
  vars_files:
    - ../group_vars/vault.yml
  roles:
    - role: ../roles/common
    - role: ../roles/postgresql_config_and_install

