# ---------------- CREATE pgBackRest FILES and DIRS ----------- #

# We use the template module to create the pgbackrest.conf file.

- name: "Configure PostgreSQL Cluster Stanza"
  ansible.builtin.template:
    src: pgbackrest.conf.j2
    dest: /etc/pgbackrest/pgbackrest.conf
    owner: postgres
    group: postgres
    mode: '0640'

# ------------------------------------------------------------- #

# ---------------- CREATE pgBackRest FILES and DIRS ----------- #

# CONFIGURE THE LOGGING - if you want other path than the default one

- name: Ensure /opt/postgresql/logs strict permissions
  ansible.builtin.file:
    path: /opt/postgresql/logs
    mode: '0700'

- name: "Create custom path for logging"
  ansible.builtin.file:
    path: /opt/postgresql/logs/pgbackrest_logs
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

# ------------------------------------------------------------- #

# ---------------- CONFIGURE LOG-PATH ------------------------- #

- name: "Configure log-path using the environment"
  ansible.builtin.command: >
    sudo -u postgres bash -c ' \
         export PGBACKREST_LOG_PATH=/opt/postgresql/logs/pgbackrest_logs && \
         pgbackrest --log-level-console=error help backup log-path'
    
# ------------------------------------------------------------- #

# ---------------- CONFIGURE pgBackRest REPO ------------------ #

- name: Set strict access permissions for /opt/postgresql/backups
  ansible.builtin.file:
    path: /opt/postgresql/backups
    mode: '0700'

# CONFIGURE THE PGBACKREST REPOSITORY

- name: "Create the pgBackRest repository"
  ansible.builtin.file:
    path: /opt/postgresql/backups/pgbackrest
    state: directory
    owner: postgres
    group: postgres
    mode: '0750'

# ------------------------------------------------------------- #

# ---------------- CREATE STANZA ------------------------------ #

- name: "Create the Stanza"
  ansible.builtin.command: >
    sudo -u postgres pgbackrest 
    --stanza=demo
    --log-level-console=info
    stanza-create

# ------------------------------------------------------------- #

# ---------------- CHECK CONFIGURATION------------------------- #

- name: "Check Configuration"
  ansible.builtin.command: >
    sudo -u postgres pgbackrest 
    --stanza=demo
    --log-level-console=info
    check
  register: check_pgbackrest_config


- name: "Print pgbackrest configuration"
  ansible.builtin.debug:
    var: check_pgbackrest_config.stdout

# ------------------------------------------------------------- #
