---
- name: "Backup info"
  gather_facts: yes
  become: yes
  vars_files:
    - group_vars/vault.yml
  vars:
    - pg_version: 13
  tasks:
    - name: "Backup info"
      ansible.builtin.command: >
        sudo -u postgres pgbackrest info
      register: backup_info

    - name: "Print backup info"
      ansible.builtin.debug:
        var: backup_info.stdout