---
- name: "Copy and Install pgBackRest Binary"
  hosts: dbs
  vars_files:
    - group_vars/vault.yml
  vars:
    - pg_version: 13
  become: true
  roles:
    - common # run all the tasks from common/tasks/main.yml
    - pgbackrest_config_and_install



