---
- name: "Ouick Start"
  hosts: dbs
  become: yes
  vars_files:
    - group_vars/vault.yml
  vars:
    - pg_version: 13
  tasks:
    # no need to create a demo cluster
    # we have to change the postgresql.conf


