---
- name: "pgBackRest build process"
  hosts: localhost
  become: yes
  vars:
    dependencies:
      - meson
      - gcc
      - postgresql13-devel
      - openssl-devel
      - libxml2-devel
      - lz4-devel
      - libzstd-devel
      - bzip2-devel
      - libyaml-devel
      - libssh2-devel
  
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: "Create build directory"
      command: mkdir -p /pgBackRest_build
    
    - name: "Download into /pgBackRest_build"
      ansible.builtin.shell: "wget -q -O - https://github.com/pgbackrest/pgbackrest/archive/release/2.55.1.tar.gz | tar zx -C /pgBackRest_build"

    - name: "Run the common role"
      import_role:
        name: common

  #  - name: "Add PostgreSQL YUM repository"
  #    ansible.builtin.get_url:
  #      url: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
  #      dest: "/tmp/pgdg-redhat-repo-latest.noarch.rpm"
  #      mode: '0664'

  # - name: "Install PostgreSQL repo"
  #   ansible.builtin.dnf:
  #     name: "/tmp/pgdg-redhat-repo-latest.noarch.rpm"
  #     state: present
  #     disable_gpg_check: yes

    - name: "Install build dependencies"
      #debug:
      #  msg: "Installing package {{ item }}"
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ dependencies }}"

    - name: "Configure pgBackRest"
      ansible.builtin.shell: >
        PKG_CONFIG_PATH=/usr/pgsql-13/lib/pkgconfig
        meson setup /pgBackRest_build/pgbackrest /pgBackRest_build/pgbackrest-release-2.55.1
      args:
        creates: "/pgBackRest_build/pgbackrest/build.ninja"


    - name: "Build pgBackRest"
      ansible.builtin.shell: "ninja -C /pgBackRest_build/pgbackrest"

