---
- name: "Setup cron jobs"
  hosts: dbs
  gather_facts: yes
  become: yes
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: "Schedule Full Backup"
      ansible.builtin.cron:
        name: "Full backup"
        user: postgres
        minute: "*/10"
        hour: "*"
        job: "pgbackrest
        --stanza=demo
        --type=full
        --log-level-console=info backup"
        state: present

    - name: "Schedule incremental backup"
      ansible.builtin.cron:
        name: "Incremental Backup"
        user: postgres
        minute: "*/5"
        hour: "*"
        job: "pgbackrest
        --stanza=demo
        --log-level-console=info backup"
        state: present

#    - name: "Schedule incremental backup"
#      ansible.builtin.cron:
#        name: "Incremental Backup"
#        minute: "*/30"
#        job: "sudo -u postgres pgbackrest
#        --stanza=demo
#        --log-level-console=info backup"
#        state: absent
