---
- name: "Setup cron jobs"
  hosts: dbs
  gather_facts: yes
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: "Schedule Full Backup"
      ansible.builtin.cron:
        name: "Full backup"
        minute: "30"
        hour: "6"
        job: "sudo -u postgres pgbackrest
        --stanza=demo
        --type=diff
        --log-level-console=info backup"

    - name: "Schedule incremental backup"
      ansible.builtin.cron:
        name: "Incremental Backup"
        minute: "*/10"
        job: "sudo -u postgres pgbackrest
        --stanza=demo
        --log-level-console=info backup"

    - name: "Schedule incremental backup"
      ansible.builtin.cron:
        name: "Incremental Backup"
        minute: "*/30"
        job: "sudo -u postgres pgbackrest
        --stanza=demo
        --log-level-console=info backup"
        state: absent
