
# ------------------- CREATE BUILD DIRECTORY ---------------- #

- name: "Create build directory"
  ansible.builtin.file:
    path: /pgBackRest_build
    state: directory
    mode: '0755'

# ------------------------------------------------------------- #

# ------------------- DOWNLOAD INTO /pgBackRest_build --------- #

- name: "Download into /pgBackRest_build"
  ansible.builtin.shell: "wget -q -O - https://github.com/pgbackrest/pgbackrest/archive/release/2.55.1.tar.gz | tar zx -C /pgBackRest_build"
#  args:
#    creates:
# ------------------------------------------------------------- #

# ------------------- INSTALL BUILD DEPENDENCIES -------------- #

- name: "Install build dependencies"
  #debug:
  #  msg: "Installing package {{ item }}"
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ dependencies }}"

# ------------------------------------------------------------- #

# ------------------- CONFIGURE pgBackRest -------------------- #

- name: "Configure pgBackRest"
  ansible.builtin.shell: >
    PKG_CONFIG_PATH=/usr/pgsql-14/lib/pkgconfig
    meson setup /pgBackRest_build/pgbackrest /pgBackRest_build/pgbackrest-release-2.55.1
  args:
    creates: "/pgBackRest_build/pgbackrest/build.ninja"

# ------------------------------------------------------------- #

# ------------------- BUILD pgBackRest ------------------------ #

- name: "Build pgBackRest"
  ansible.builtin.shell: "ninja -C /pgBackRest_build/pgbackrest"

# ------------------------------------------------------------- #