- name: "Check for the base VMs"
  ansible.builtin.win_command: vboxmanage list vms
  register: vms_list

- name: "Debug the 'vms_list' variable"
  ansible.builtin.debug:
    var: vms_list

- name: "Search for the bronze-base VMs"
  ansible.builtin.set_fact:
    bronze_base: > 
      {{ (result | first | default('') | split('"'))[0] if result | length > 0 else 'VM_NOT_FOUND' }}
  vars:
    search_string: "bronze-base"
    result: "{{ vms_list.stdout_lines | select('search', search_string) | list}}"

- name: "Debug the 'bronze_base' variable"
  ansible.builtin.debug:
    var: bronze_base

