- name: "Check for the base VMs"
  ansible.builtin.win_command: vboxmanage list vms
  register: vms_list

- name: "Debug the 'vms_list' variable"
  ansible.builtin.debug:
    var: vms_list

- name: "Search for the bronze-base VMs"
  ansible.builtin.set_fact:
    bronze_base: > 
      {{ (bronze_result | first | default('') | split('"'))[0] if bronze_result | length > 0 else 'VM_NOT_FOUND' }}
    silver_base: > 
      {{ (silver_result | first | default('') | split('"'))[0] if silver_result | length > 0 else 'VM_NOT_FOUND' }}
    gold_base: >
      {{ (gold_result | first | default('') | split('"'))[0] if gold_result | length > 0 else 'VM_NOT_FOUND' }}
  vars:
    bronze_search_string: "bronze-base"
    silver_search_string: "silver-base"
    gold_search_string: "gold-base"
    bronze_result: "{{ vms_list.stdout_lines | select('search', bronze_search_string) | list}}"
    silver_result: "{{ vms_list.stdout_lines | select('search', silver_search_string) | list}}"
    gold_result: "{{ vms_list.stdout_lines | select('search', gold_search_string) | list}}"

- name: "Debug the 'bronze_base' variable"
  ansible.builtin.debug:
    var: "{{ item }}"
  loop:
    - bronze_base
    - silver_base
    - gold_base

- name: "Create base VMs if they do not exist"
  when:
    - bronze_base is defined and bronze_base == 'VM_NOT_FOUND'
    - silver_base is defined and silver_base == 'VM_NOT_FOUND'
    - gold_base is defined and gold_base == 'VM_NOT_FOUND'
  block:
    - name: "Create Vagrantfile"
      ansible.windows.win_template:
        src: Vagrantfile.j2
        dest: C:\Users\Andrei\Desktop\Vagrantfile
    - name: "Generate base VMs"
      ansible.builtin.win_command: vagrant up


