# ------------------ LIST VMs --------------------------------- #

- name: "List the virtual machines on the Hypervisor Host"
  ansible.builtin.win_command: vboxmanage list vms
  register: vms_list

- name: "Debug the 'vms_list' variable"
  ansible.builtin.debug:
    var: vms_list

# ------------------------------------------------------------- #

# ------------------ CHECK BASE VMs --------------------------- #

# Check if the base VMs exist. If not, create them.

- name: "Check base VMs"
  ansible.builtin.import_role:
    name: host_hypervisor_management
    tasks_from: check_base_vms

# ------------------------------------------------------------- #

# ------------------ SET VM INFO ------------------------------ #

# need to change this data with something more dynamic

- name: "Set new VM info"
  ansible.builtin.set_fact:
    vm_data:
      vm_base: "bronze"
      vm_name: "bronze_1"
      base_folder: "D:\\VMs"

# ------------------------------------------------------------- #

# ------------------ CREATE VM -------------------------------- #

- name: "Create a new VM using a designated base"
  ansible.builtin.win_command: >
    vboxmanage clonevm {{ vm_data.vm_base }} --name {{ vm_data.vm_name }} --basefolder={{ vm_data.base_folder }} --register
  args:
    creates: "{{ vm_data.base_folder }}\\{{ vm_data.vm_name }}\\{{ vm_data.vm_name }}.vbox"
  register: clonevm_output

- name: "Debug the 'clonevm_output' variable"
  ansible.builtin.debug:
    var: clonevm_output

# ------------------------------------------------------------- #

# ------------------ START VM --------------------------------- #

- name: "Start the {{ vm_data.vm_name }} VM"
  ansible.builtin.win_command: >
    vboxmanage startvm {{ vm_data.vm_name }}

# ------------------------------------------------------------- #

# ------------------ GET MAC ---------------------------------- #

- name: "Obtain the formatted MAC"
  ansible.builtin.import_role:
    name: host_hypervisor_management
    tasks_from: get_MAC_address
  vars:
    vm_name: "{{ vm_data.vm_name }}"

# ------------------------------------------------------------- #
