- name: "List the virtual machines on the Hypervisor Host"
  ansible.builtin.win_command: vboxmanage list vms
  register: vms_list

- name: "Debug the 'vms_list' variable"
  ansible.builtin.debug:
    var: vms_list

- name: Create a new VM using a designated base
  vars:
    vm_base: "RedHat-Base"
    vm_name: "RedHat_Test"
    base_folder: "D:\\VMs"
  ansible.builtin.win_command: >
    vboxmanage clonevm {{ vm_base }} --name {{ vm_name }} --basefolder={{ base_folder }} --register
  args:
    creates: "{{ base_folder }}{{ vm_name }}"
  register: clonevm_output

- name: "Debug the 'clonevm_output' variable"
  ansible.builtin.debug:
    var: clonevm_output