- name: "List the virtual machines on the Hypervisor Host"
  ansible.builtin.win_command: vboxmanage list vms
  register: vms_list

- name: "Debug the 'vms_list' variable"
  ansible.builtin.debug:
    var: vms_list

- name: "Set new VM info"
  ansible.builtin.set_fact:
    vm_data:
      vm_base: "RedHat-Base"
      vm_name: "RedHat-Test-1"
      base_folder: "D:\\VMs"

- name: Create a new VM using a designated base
  ansible.builtin.win_command: >
    vboxmanage clonevm {{ vm_data.vm_base }} --name {{ vm_data.vm_name }} --basefolder={{ vm_data.base_folder }} --register
  args:
    creates: "{{ vm_data.base_folder }}\\{{ vm_data.vm_name }}\\{{ vm_data.vm_name }}.vbox"
  register: clonevm_output

- name: "Debug the 'clonevm_output' variable"
  ansible.builtin.debug:
    var: clonevm_output

- name: "Start the {{ vm_data.vm_name }} VM"
  ansible.builtin.win_command: >
    vboxmanage startvm {{ vm_data.vm_name }}

- name: "Get info of the newly created VM"
  ansible.builtin.win_command: >
    vboxmanage showvminfo {{ vm_data.vm_name }}
  register: showvminfo_output

- name: "Debug the 'showvminfo_output' variable"
  ansible.builtin.debug:
    var: showvminfo_output

- name: "Get the MAC address"
  ansible.builtin.set_fact:
    mac_address: "{{ ((showvminfo_output.stdout_lines | select('search', 'MAC') | list | first | split(': '))[2] | split(','))[0] }}"

- name: "Debug the 'mac_address' variable"
  ansible.builtin.debug:
    var: mac_address

- name: "Format the MAC address"
  ansible.builtin.set_fact:
    formatted_mac_address: "{{ mac_address | regex_replace('..(?!$)', '\\0:') | lower }}"

- name: "Debug the 'formatted_mac_address' variable"
  ansible.builtin.debug:
    var: formatted_mac_address
