# Configure the subscription-manager

- name: "Configure the subscription-manager"
  ansible.builtin.shell: >
    subscription-manager register
    --username={{ redhat_username }}
    --password={{ redhat_password }}
    --auto-attach
  register: register_output
  failed_when: "'Invalid username or password' in register_output.stderr"

- ansible.builtin.shell: "subscription-manager attach --auto"

# UPDATE DNF

- name: "Update DNF"
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: yes
    update_cache: true
    nobest: yes

# Install the official PostgreSQL Repo - we will use it later to install PostgreSQL on the slave nodes

- name: "Install the repository RPM"
  ansible.builtin.dnf:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
    disable_gpg_check: yes

# enable the codeready repo

- name: "Enable codeready-builder(CRB) repo"
  ansible.builtin.command: >
    subscription-manager repos --enable codeready-builder-for-rhel-9-x86_64-rpms
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "9"

- name: "Install EPEL repository (RHEL 9)"
  block:
    - name: "Download and install EPEL release RPM"
      ansible.builtin.dnf:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
        state: present
        disable_gpg_check: yes

    - name: "Import EPEL GPG key"
      ansible.builtin.rpm_key:
        key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9"
        state: present