# -------------------- CREATE/RESIZE VG --------------------- #

# DOCS:
# https://docs.ansible.com/projects/ansible/latest/collections/community/general/lvg_module.html

# DESCRIPTION:
# This task creates a Volume Group (VG)

# Our purpose for the moment is to create only one VG from which
# we will create the LVMs for the PostgreSQL database.

- name: Create or resize a volume group on top of /dev/sdb1 and /dev/sdc5.
  community.general.lvg:
    vg: '{{ vg_name }}'
    pvs: '{{ physical_volume }}'
    state: present

# ----------------------------------------------------------- #
