# -------------------- CONFIGURE LOGICAL VOLUMES --------------- #

# DOCS:
# https://docs.ansible.com/projects/ansible/latest/collections/ansible/posix/mount_module.html

# DESCRIPTION:
# Calculate the space needed for each LVM:
# 4 PostgreSQL LVMs and 4 LVMs for snapshots
# VG space / 8 = space for 1 LVM

#UPDATE: if there are any LVMs, we create NOTHING, we do not 4
# recreate them

# CHECK THE LVM LIST

- name: "Create PostgreSQL LVM name list"
  ansible.builtin.set_fact:
    postgresql_lvms:
      - lvm_pg_data
      - lvm_pg_wal
      - lvm_pg_logs
      - lvm_pg_backups

- name: "Execute 'lvs' command"
  ansible.builtin.command: >
    lvs --noheadings --units g
    -o lv_name,vg_name,lv_size,lv_path
  register: lvs_output

- name: "Debug the 'lvs_output' variable"
  ansible.builtin.debug:
    var: lvs_output.stdout_lines[2:]
  when: lvs_output is defined

- name: "Create list with existing non-standard LVMs"
  ansible.builtin.set_fact:
    existing_lvms: "{{ existing_lvms | default([]) + [
      item.split()[0]
    ] }}"
  loop: "{{ lvs_output.stdout_lines[2:] }}"
  when: lvs_output is defined

- name: "Debug the 'existing_lvms' list"
  ansible.builtin.debug:
    var: existing_lvms
  when: existing_lvms is defined

- name: "Check if the 'postgresql_lvms' and 'existing_lvms' are the same"
  ansible.builtin.set_fact:
    number_of_non_existing_lvms: "{{ postgresql_lvms | difference(existing_lvms) | length | int }}"
  when:
    - existing_lvms is defined
    - postgresql_lvms is defined

- name: "Debug the 'number_of_non_existing_lvms' variable"
  ansible.builtin.debug:
    var: number_of_non_existing_lvms
  when: number_of_non_existing_lvms is defined

# IF THERE ARE ALREADY LVMS
# The VG should already have the size increased (need to check)
# We do not extend/shrink the LVMs here.
# The extend/shrink should be separate procedure(s).

- name: "Debug the fact that ALL LVMs already exist"
  ansible.builtin.debug:
    msg: "SUCCESS: The data, logs, wal and backups LVMs already exist."
  when:
    - number_of_non_existing_lvms is defined
    - number_of_non_existing_lvms | int == 0

- name: "Debug the fact that NOT ALL LVMs already exist"
  ansible.builtin.debug:
    msg:
      - "ERROR: Some of the data, logs, wal and backups LVMs DO NOT exist. "
      - "TO DO: Please check which LVMs are missing and proceed with caution!"
  when:
    - number_of_non_existing_lvms is defined
    - postgresql_lvms | length | int != number_of_non_existing_lvms | int
    - number_of_non_existing_lvms | int != 0

# IF THERE ARE NO LVMs, BUT NEW EMPTY DISKS:
# 1) Create the LVMs
# 2) Create XFS file systems on LVMs
# 3) Mount the File Systems

- name: "Create LVMs if they do not exist"
  when:
    - number_of_non_existing_lvms is defined
    - postgresql_lvms | length | int == number_of_non_existing_lvms | int
  block:
    - name: "1.1) Get the output of the vgdisplay"
      ansible.builtin.command: vgdisplay vg_postgres
      register: vgdisplay_output

    - name: "1.2) Set fact that contains Total PE"
      ansible.builtin.set_fact:
        total_PE: '{{ (result[0] | split)[2] }}'
      vars:
        search_string: 'Total PE'
        result: "{{ vgdisplay_output.stdout_lines | select('search', search_string) | list }}"
      when: vgdisplay_output.rc == 0

    - name: "1.3) Set fact that contains Free PE"
      ansible.builtin.set_fact:
        free_PE: '{{ (result[0] | split)[4] }}'
      vars:
        search_string: 'Free  PE / Size'
        result: "{{ vgdisplay_output.stdout_lines | select('search', search_string) | list }}"
      when: vgdisplay_output.rc == 0

    - name: "1.4) Debug Total PE and Free PE"
      ansible.builtin.debug:
        msg:
          - "Total PE: {{ total_PE }}"
          - "Free PE: {{ free_PE }}"
      when: vgdisplay_output.rc == 0

    - name: "1.5) Calculate the size for one LVM (the PE approach)"
      ansible.builtin.set_fact:
        lvm_size_mb: "{{ (free_PE | int * 4) // 8 }}"
      when: vgdisplay_output.rc == 0

    - name: "1.6) Debug LVM PE size"
      ansible.builtin.debug:
        msg:
          - "The LVM size is: {{ lvm_size_mb }}"
      when: vgdisplay_output.rc == 0

    - name: "1.7) Create Logical Volumes (LVMs)"
      community.general.lvol:
        vg: vg_postgres
        lv: "{{ item }}"
        size: "{{ lvm_size_mb }}M"
        state: present
      loop: '{{ postgresql_lvms }}'
      when: vgdisplay_output.rc == 0

    - name: "1.8) Create XFS file systems on the LVMs"
      ansible.builtin.command: "mkfs.xfs /dev/vg_postgres/{{ item }}"
      loop: '{{ postgresql_lvms }}'
      when: vgdisplay_output.rc == 0
      
    - name: "1.9) Create PostgreSQL mount dir list"
      ansible.builtin.set_fact:
        postgresql_dirs:
          - /opt/postgresql/data
          - /opt/postgresql/wal
          - /opt/postgresql/logs
          - /opt/postgresql/backups

    - name: "1.10) Create PostgreSQL directories if it does not exist"
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        mode: '0755'
      loop: '{{ postgresql_dirs }}'

    - name: "1.11) Mount LVM File Systems"
      ansible.posix.mount:
        path: "{{ item.1 }}"
        src: "/dev/vg_postgres/{{ item.0 }}"
        fstype: xfs
        state: mounted
      loop: "{{ postgresql_lvms | zip(postgresql_dirs) | list }}"  
    
# ----------------------------------------------------------- #
