# Create LVM

- name: Create Logical Volume (LVM)
  ansible.builtin.command: "lvcreate -l '{{ lvm_PE_size }}' -n '{{ lvm_name }}' '{{ vg_name }}'"
  register: lvcreate_output

- name: Debug lvcreate output
  ansible.builtin.debug:
    var: lvcreate_output
