# This task creates a Physical Volume (PV)

- name: Create Physical Volumes (PV)
  community.general.lvm_pv:
    device: '{{ partition }}'
    state: present
  register: create_physical_volume_output
  when: partition is defined

- name: Output of the 'Create Physical Volume (PV)' task
  ansible.builtin.set_fact:
    create_pvs_status: "{{ create_pvs_status | default([]) + [
      create_physical_volume_output
    ] }}"
  when: partition is defined