
# Need to configure the creation of multiple partitions

- name: Create_New_XFS_Primary_Partition
  community.general.parted:
    device: /dev/{{ item }}
    number: 1
    state: present
    fs_type: xfs
  register: create_partition_output
  loop: "{{ empty_disks }}"

# After creating multiple partitions, use set_fact to save them inside a list

- name: Output partition number task
  ansible.builtin.debug:
    var: create_partition_output['results'][0]['partitions'][0]['num']

- name: Output disk where partition was created
  ansible.builtin.debug:
    var: create_partition_output['results'][0]['disk']['dev']

