# -------------------- CREATE XFS PARTITIONS ---------------- #

# DOCS:
# https://docs.ansible.com/projects/ansible/latest/collections/community/general/parted_module.html

# DESCRIPTION:
# This task creates 'number_of_partitions_per_disk' partitions
# for each 'empty' disk.

# One important thing to mention here is the use of 'loop_control'
# option. We use this option because we have nested loops and when
# we want to use the {{ item }} Jinja2 syntax, the item from the
# task below will shadow the item from the upper loop.

- name: Create XFS Primary Partitions
  community.general.parted:
    device: /dev/{{ disk_name }}
    number: "{{ part_number }}"
    flags: [lvm]
    state: present
    fs_type: xfs
    part_start: "{{ ((part_number - 1) * 100 / number_of_partitions_per_disk) | int }}%"
    part_end: "{{ (part_number * 100 / number_of_partitions_per_disk) | int }}%"
  register: create_partition_output
  loop: "{{ range(1, number_of_partitions_per_disk + 1) | list }}"
  loop_control:
    loop_var: part_number

# ----------------------------------------------------------- #

# -------------------- RELOAD PARTITION TABLE---------------- #

- name: Reload the partition table
  ansible.builtin.command: 'partprobe /dev/{{ disk_name }}'
  changed_when: false

# -------------------- CREATE 'partitions_created' FACT ----- #

# DOCS:
# https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/set_fact_module.html

# DESCRIPTION:
# We create the 'partitions_created' fact.
# We will use this fact when we will create the Physical
# Volumes (PV).

- name: Create fact that contains the new partitions
  ansible.builtin.set_fact:
    partitions_created: "{{ partitions_created | default([]) + [
      '/dev/' ~ disk_name ~ part_number
    ] }}"
  loop: "{{ range(1, number_of_partitions_per_disk + 1) | list }}"
  loop_control:
    loop_var: part_number

# ----------------------------------------------------------- #
