- name: Read device information (always use unit when probing)
  community.general.parted: device=/dev/sdb unit=MiB
  register: sdb_info

- name: Remove all partitions from disk
  community.general.parted:
    device: '{{ disk }}'
    number: '{{ part.num }}'
    state: absent
  loop: '{{ sdb_info.partitions }}'
  loop_control:
    loop_var: part
