- name: Delete_XFS_partition_from_/dev/sdb_disk
  community.general.parted:
    device: /dev/sdb
    number: 1
    state: absent
  register: delete_xfs_partition_output

- name: Output of 'Delete_XFS_partition_from_/dev/sdb_disk' task
  ansible.builtin.debug:
    var: delete_xfs_partition_output
