- name: Check if /etc/fstab file exists
  ansible.builtin.stat:
    path: /etc/fstab
  register: fstab_check

- name: Check the contents of fstab
  ansible.builtin.command: cat /etc/fstab
  register: fstab_contents
  when: fstab_check.stat.exists

- name: Output the contents of /etc/fstab
  ansible.builtin.debug:
    var: fstab_contents.stdout_lines
  when: fstab_check.stat.exists

- name: Get the lines that contain specific substrings
  ansible.builtin.debug:
    msg: '{{ item }}'
  when: "'lvm_pg_data' in item"
  loop: '{{ fstab_contents.stdout_lines }}'
