- name: Check if /etc/fstab file exists
  ansible.builtin.stat:
    path: /etc/fstab
  register: fstab_check

- name: Check the contents of fstab
  ansible.builtin.command: cat /etc/fstab --reportformat json
  register: fstab_contents
  when: fstab_check.stat.exists

- name: Output the contents of /etc/fstab
  ansible.builtin.debug:
    var: fstab_contents
  when: fstab_check.stat.exists
