---
- name: Check the storage devices
  ansible.builtin.debug:
    var: ansible_facts.devices

- name: Create empty_disks list
  ansible.builtin.set_fact:
    empty_disks: >- 
      {{ 
        ansible_facts.devices 
        | dict2items
        | selectattr('value.partitions', 'equalto', {}) 
        | selectattr('value.model', 'equalto', "VBOX HARDDISK")
        | map(attribute='key')
        | list 
      }}

- name: List the empty_disks list
  ansible.builtin.debug:
    var: empty_disks

- name: Create XFS partition
  ansible.builtin.import_role:
    name: storage_management
    tasks_from: create_partition
  when: empty_disks is defined and empty_disks | length > 0

- name: Output New XFS Partition Name
  ansible.builtin.debug:
    var: new_partition
  when: empty_disks is defined and empty_disks | length > 0

- name: Delete XFS partition
  ansible.builtin.import_role:
    name: storage_management
    tasks_from: delete_partition
  when: empty_disks is defined and empty_disks | length == 0

#- name: Create Physical Volume (PV)
#  ansible.builtin.shell: sudo pvcreate /dev/sdb1