---
- name: "pgBackRest build process"
  hosts: localhost
  become: yes
  vars:
    dependencies:
      - meson
      - gcc
      - postgresql13-devel
      - openssl-devel
      - libxml2-devel
      - lz4-devel
      - libzstd-devel
      - bzip2-devel
      - libyaml-devel
      - libssh2-devel
  
  vars_files:
    - ../group_vars/vault.yml
  roles:
    - pgbackrest_build


