- name: "Install PostgreSQL version {{ pg_version }}"
  ansible.builtin.dnf:
    name: postgresql{{ pg_version }}-server
    state: present

- name: "Initialize the database"
  ansible.builtin.command: "/usr/pgsql-{{ pg_version }}/bin/postgresql-{{ pg_version }}-setup initdb"
  args:
    creates: /var/lib/pgsql/{{ pg_version }}/data/PG_VERSION

#- name: "Start the PostgreSQL service"
#  ansible.builtin.service:
#    name: postgresql-{{ pg_version }}
#    state: started
#
#- name: "Start the PostgreSQL service"
#  ansible.builtin.service:
#    name: postgresql-{{ pg_version }}
#    state: stopped

- name: Ensure /opt is accessible
  ansible.builtin.file:
    path: /opt
    mode: '0755'

- name: Ensure /opt/postgresql is accessible
  ansible.builtin.file:
    path: /opt/postgresql
    mode: '0755'

- name: Ensure ownership recursively
  ansible.builtin.file:
    path: /opt/postgresql
    owner: postgres
    group: postgres
    recurse: yes

- name: Set Strict permissions on PGDATA
  ansible.builtin.file:
    path: /opt/postgresql/data
    mode: '0700'

- name: "Rsync the data from old to new location"
  ansible.builtin.command: rsync -av /var/lib/pgsql/{{ pg_version }}/data/ /opt/postgresql/data

- name: "Create postgresql-14.service.d folder"
  ansible.builtin.file:
    path: /etc/systemd/system/postgresql-{{ pg_version }}.service.d
    state: directory

- name: "Update the postgresql-{{ pg_version }} conf"
  ansible.builtin.template:
    src: postgresql-service.conf.j2
    dest: /etc/systemd/system/postgresql-{{ pg_version }}.service.d/postgresql-service.conf

- name: "Set SELINUX on permissive mode"
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: "Apply same context to the new data location"
  ansible.builtin.shell: | 
    semanage fcontext --add --equal /var/lib/pgsql /opt/postgresql
    restorecon -rv /opt/postgresql

- name: "Set SELINUX on permissive mode"
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: "Upload postgresql.conf config file from template"
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/{{ pg_version }}/data/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0644'

- name: "Enable automatic start"
  ansible.builtin.service:
    name: postgresql-{{ pg_version }}
    enabled: yes

- name: "Start the PostgreSQL service"
  ansible.builtin.service:
    name: postgresql-{{ pg_version }}
    state: started




