---
- name: Test 'pgbackrest_build' role
  gather_facts: no
  hosts: localhost
  become: yes
  vars_files:
    - ../group_vars/vault.yml
  vars:
    dependencies:
        - meson
        - gcc
        - postgresql14-devel
        - openssl-devel
        - libxml2-devel
        - lz4-devel
        - libzstd-devel
        - bzip2-devel
        - libyaml-devel
        - libssh2-devel
    pg_version: 14
  roles:
    - role: ../roles/pgbackrest_build

