# -------------------------------------------------------------------------------------------- #
# ---------------------------------------- PERFORM FULL BACKUP ------------------------------- #
# -------------------------------------------------------------------------------------------- #

---
- name: "Perform full backup for {{ db_instance }}"
  hosts: "{{ db_instance }}"
  become: yes
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: "Perform full backup"
      ansible.builtin.import_role:
        name: pgbackrest_actions
        tasks_from: full_backup
    - name: "Perform API call to update the Backup Info for {{ db_instance }}"
      ansible.builtin.command: pgbackrest info
      become_user: postgres
      register: backup_info
    - name: "Debug 'backup_info' variable"
      ansible.builtin.debug:
        var: backup_info


# -------------------------------------------------------------------------------------------- #
# -------------------------------------------------------------------------------------------- #
# -------------------------------------------------------------------------------------------- #
