---
- name: "Perform differential backup"
  hosts: dbs
  become: yes
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: "Perform differential backup"
      ansible.builtin.import_role:
        name: pgbackrest_actions
        tasks_from: diff_backup
