# -------------------------------------------------------------------------------------------- #
# ---------------------------------------- PERFORM FULL BACKUP ------------------------------- #
# -------------------------------------------------------------------------------------------- #

---
- name: "Perform full backup for {{ db_instance }}"
  hosts: "{{ db_instance }}"
  become: yes
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: "Perform full backup"
      ansible.builtin.import_role:
        name: pgbackrest_actions
        tasks_from: full_backup
    - name: "Get the pgBackRest backup data"
      ansible.builtin.command: pgbackrest info
      become_user: postgres
      register: backup_info
    - name: "Debug 'backup_info' variable"
      ansible.builtin.debug:
        var: backup_info.stdout_lines
    - name: "Backup Info"
      ansible.builtin.set_fact:
        formatted_backup_info:
          stanza: "{{ (backup_info.stdout_lines[0] | split(': '))[1] }}"
          type: "{{ (backup_info.stdout_lines[7] | split(': '))[0] | regex_replace(' ','') }}"
          backup_id: "{{ (backup_info.stdout_lines[7] | split(': '))[1] }}"
          start_time: "{{ ((backup_info.stdout_lines[8] | split(': '))[1] | split(' / '))[0] }}"
          stop_time: "{{ ((backup_info.stdout_lines[8] | split(': '))[1] | split(' / '))[1] }}"
          wal_start: "{{ ((backup_info.stdout_lines[9] | split(': '))[1] | split(' / '))[0] }}"
          wal_stop: "{{ ((backup_info.stdout_lines[9] | split(': '))[1] | split(' / '))[1] }}"
          db_size_mb: "{{ ((backup_info.stdout_lines[10] | split(','))[0] | split(': '))[1] }}"
          backup_size_mb: "{{ ((backup_info.stdout_lines[10] | split(','))[1] | split(': '))[1] }}"
          repo1:
            backup_set_size: "{{ ((backup_info.stdout_lines[11] | split(': '))[2] | split(','))[0] }}"
            backup_size: "{{ (backup_info.stdout_lines[11] | split(': '))[3] }}"


    - name: "Debug 'formatted_backup_info' variable"
      ansible.builtin.debug:
        var: formatted_backup_info

    - name: "Perform API call to update the Backup Info for {{ db_instance }}"
      ansible.builtin.uri:
        url: "http://127.0.0.1:9001/api/backups/{{ backup_id }}/"
        method: PATCH
        user: "{{ django_admin }}"
        password: "{{ django_password }}"
        force_basic_auth: yes
        body_format: json
        body:
          stanza: "{{ formatted_backup_info.stanza }}"
          backup_type: "{{ formatted_backup_info.type }}"
          backup_id: "{{ formatted_backup_info.backup_id }}"
          start_time: "{{ formatted_backup_info.start_time }}"
          stop_time: "{{ formatted_backup_info.stop_time }}"
          wal_start: "{{ formatted_backup_info.wal_start }}"
          wal_stop: "{{ formatted_backup_info.wal_stop }}"
          db_size_mb: "{{ formatted_backup_info.db_size_mb }}"
          backup_size_mb: "{{ formatted_backup_info.backup_size_mb }}"
          backup_set_size: "{{ formatted_backup_info.repo1.backup_set_size }}"
          backup_size: "{{ formatted_backup_info.repo1.backup_size }}"
        status_code: [ 200, 204 ]
      delegate_to: localhost


# -------------------------------------------------------------------------------------------- #
# -------------------------------------------------------------------------------------------- #
# -------------------------------------------------------------------------------------------- #
