# -------------------------------------------------------------------------------------------- #
# ---------------------------------------- PERFORM FULL BACKUP ------------------------------- #
# -------------------------------------------------------------------------------------------- #

---
- name: "Perform full backup for {{ db_instance }}"
  hosts: "{{ db_instance }}"
  become: yes
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: "Perform full backup"
      ansible.builtin.import_role:
        name: pgbackrest_actions
        tasks_from: full_backup
    - name: "Perform API call to update the Backup Info for {{ db_instance }}"
      ansible.builtin.command: pgbackrest info
      become_user: postgres
      register: backup_info
    - name: "Debug 'backup_info' variable"
      ansible.builtin.debug:
        var: backup_info.stdout_lines
    - name: "Backup Info"
      ansible.builtin.set_fact:
        formatted_backup_info:
          stanza: "{{ (backup_info.stdout_lines[0] | split(': '))[1] }}"
          type: "{{ (backup_info.stdout_lines[7] | split(': '))[0] | regex_replace(' ','') }}"
          backup_id: "{{ (backup_info.stdout_lines[7] | split(': '))[1] }}"
          time: "{{ (backup_info.stdout_lines[8] | split(': '))[1] }}"
          start_time: "{{ ((backup_info.stdout_lines[8] | split(': '))[1] | split(' / '))[0] }}"
          stop_time: "{{ ((backup_info.stdout_lines[8] | split(': '))[1] | split(' / '))[1] }}"

    - name: "Debug 'formatted_backup_info' variable"
      ansible.builtin.debug:
        var: formatted_backup_info

# -------------------------------------------------------------------------------------------- #
# -------------------------------------------------------------------------------------------- #
# -------------------------------------------------------------------------------------------- #
