---
- name: "Perform incremental backup"
  hosts: dbs
  become: yes
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: "Perform incremental backup"
      ansible.builtin.import_role:
        name: pgbackrest_actions
        tasks_from: incr_backup
