# -------------------------------------------------------------------------------------------- #
# ---------------------------------------- CREATE NEW VM ------------------------------------- #
# -------------------------------------------------------------------------------------------- #
---
- name: "Create new VM"
  hosts: hypervisor
  gather_facts: no
  tasks:
    - name: "Create New VM"
      ansible.builtin.import_role:
        name: host_hypervisor_management
        tasks_from: create_new_vm

# -------------------------------------------------------------------------------------------- #
# ---------------------------------------- UPDATE INV ---------------------------------------- #
# -------------------------------------------------------------------------------------------- #

- name: "Add the New VM to static inventory"
  hosts: localhost
  gather_facts: no
  become: yes
  vars_files:
    - group_vars/vault.yml
  vars:
    vm_name: "{{ vm_name_user_input | default(hostvars['hypervisor'].vm_data.vm_name) }}"
    formatted_mac_address: "{{ hostvars['hypervisor'][(hostvars['hypervisor'].vm_data.vm_name | replace('-', '_')) ~ '_formatted_mac_address'] }}"
    inventory_name: "slave_nodes_inventory"
    dinamic_group_name: new_slaves
    static_group_name: slaves
  tasks:
    - name: "Add the New VM to static inventory"
      ansible.builtin.include_role:
        name: host_hypervisor_management
        tasks_from: add_vm_to_inventory

    - name: "What IP address is sent to Django?"
      ansible.builtin.debug:
        msg: "The IP detected is: {{ new_vm_ip_address }}"

    - name: "Send the IP Address back to Django API"
      ansible.builtin.uri:
        url: "http://127.0.0.1:9001/api/vms/{{ vm_id }}/"
        method: PATCH
        user: "{{ django_admin }}"
        password: "{{ django_password }}"
        force_basic_auth: yes
        body_format: json
        body:
          ipv4_address: "{{ new_vm_ip_address }}"
        status_code: [ 200, 204 ]

    - name: "Add the new PostgreSQL instance to the DB"
      vars:
        vm_id: "{{ vm_id }}"
        port_input: "5432"
        version_input: "14.23"
      ansible.builtin.include_role:
        name: django_api_client
        tasks_from: insert_psql_instance

- name: "Insert the PostgreSQL instance DBS into API database (DAY 0)"
  hosts: new_slaves
  gather_facts: no
  become: yes
  become_user: postgres
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: "Get all PostgreSQL Databases details"
      ansible.builtin.command: >
        psql -At -F '|' -c "
        SELECT d.datname, 
              pg_catalog.pg_get_userbyid(d.datdba), 
              pg_catalog.pg_encoding_to_char(d.encoding), 
              d.datcollate, 
              d.datctype, 
              pg_catalog.array_to_string(d.datacl, ';'), 
              pg_catalog.pg_size_pretty(pg_catalog.pg_database_size(d.datname)), 
              t.spcname, 
              regexp_replace((SELECT description FROM pg_catalog.pg_shdescription WHERE objoid = d.oid AND classoid = 'pg_database'::regclass), '[\r\n]+', ' ', 'g') 
        FROM pg_catalog.pg_database d 
        JOIN pg_catalog.pg_tablespace t ON d.dattablespace = t.oid 
        ORDER BY 1;"
      register: instance_databases_output

    - name: "Debug the 'instance_databases_output' variable"
      ansible.builtin.debug:
        var: instance_databases_output.stdout_lines

    - name: "Interact with Django API on localhost"
      delegate_to: localhost
      become: no
      block:
        - name: "Get PostgreSQL instance"
          vars:
            vm_id: "{{ vm_id }}"
          ansible.builtin.include_role:
            name: django_api_client
            tasks_from: get_psql_instance

        - name: "Insert existing DBs"
          vars:
            vm_id: "{{ vm_id }}"
            fetched_instance_url_global: "{{ instance_get_output.json[0].url }}"
          ansible.builtin.include_role:
            name: django_api_client
            tasks_from: insert_psql_dbs_day_0
          loop: "{{ instance_databases_output.stdout_lines }}"

# -------------------------------------------------------------------------------------------- #
# ---------------------------------------- COPY SSH KEY M > S -------------------------------- #
# -------------------------------------------------------------------------------------------- #

- name: "Copy the public SSH key from master to the new slave"
  hosts: new_slaves
  gather_facts: no
  become: yes
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: "Copy key"
      ansible.builtin.import_role:
        name: host_hypervisor_management
        tasks_from: copy_ssh_key
