# -------------------------------------------------------------------------------------------- #
# ---------------------------------------- CREATE NEW VM ------------------------------------- #
# -------------------------------------------------------------------------------------------- #
---
- name: "Create new VM"
  hosts: hypervisor
  gather_facts: no
  tasks:
    - name: "Create New VM"
      ansible.builtin.import_role:
        name: host_hypervisor_management
        tasks_from: create_new_vm

# -------------------------------------------------------------------------------------------- #
# ---------------------------------------- UPDATE INV ---------------------------------------- #
# -------------------------------------------------------------------------------------------- #

- name: "Add the New VM to static inventory"
  hosts: localhost
  gather_facts: no
  become: yes
  vars_files:
    - group_vars/vault.yml
  vars:
    vm_name: "{{ vm_name_user_input | default(hostvars['hypervisor'].vm_data.vm_name) }}"
    formatted_mac_address: "{{ hostvars['hypervisor'][(hostvars['hypervisor'].vm_data.vm_name | replace('-', '_')) ~ '_formatted_mac_address'] }}"
    inventory_name: "slave_nodes_inventory"
    dinamic_group_name: new_slaves
    static_group_name: slaves
  tasks:
    - name: "Add the New VM to static inventory"
      ansible.builtin.include_role:
        name: host_hypervisor_management
        tasks_from: add_vm_to_inventory

    - name: "What IP address is sent to Django?"
      ansible.builtin.debug:
        msg: "The IP detected is: {{ new_vm_ip_address }}"

    - name: "Send the IP Address back to Django API"
      ansible.builtin.uri:
        url: "http://127.0.0.1:9001/api/vms/{{ vm_id }}/"
        method: PATCH
        user: "{{ django_admin }}"
        password: "{{ django_password }}"
        force_basic_auth: yes
        body_format: json
        body:
          ipv4_address: "{{ new_vm_ip_address }}"
        status_code: [ 200, 204 ]

    - name: "Add the new PostgreSQL instance to the DB"
      ansible.builtin.uri:
        url: "http://127.0.0.1:9001/api/instances/"
        method: POST
        user: "{{ django_admin }}"
        password: "{{ django_password }}"
        force_basic_auth: yes
        body_format: json
        body:
          port: 5432
          version: 14.23
          vm: "{{ base_vm_name_user_input }}-{{ vm_name_user_input }}"

- name: "Get the DBs of the PostgreSQL instance"
  hosts: new_slaves
  gather_facts: no
  become: yes
  become_user: postgres
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: "Perform '\l+' over the PostgreSQL instance"
      ansible.builtin.command: psql -c "\l+"
      register: instance_databases_output
    - name: "Debug the 'instance_databases_output' variable"
      ansible.builtin.debug:
        var: instance_databases_output.stdout_lines

# -------------------------------------------------------------------------------------------- #
# ---------------------------------------- COPY SSH KEY M > S -------------------------------- #
# -------------------------------------------------------------------------------------------- #

- name: "Copy the public SSH key from master to the new slave"
  hosts: new_slaves
  gather_facts: no
  become: yes
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: "Copy key"
      ansible.builtin.import_role:
        name: host_hypervisor_management
        tasks_from: copy_ssh_key
