---
- name: "Remove VM"
  hosts: hypervisor
  gather_facts: no
  tasks:
    - name: "Stop VM"
      ansible.builtin.win_command: vboxmanage controlvm RedHat-Test-1 poweroff

    - name: "Unregister VM"
      ansible.builtin.win_command: vboxmanage unregistervm "RedHat-Test-1" --delete