---
- name: "Start PostgreSQL service"
  hosts: dbs
  vars_files: 
    - group_vars/vault.yml
  vars:
    pg_version: 13
  become: yes
  tasks:
    - name: "Check Postgresql-{{ pg_version }}"
      shell: "systemctl status postgresql-{{ pg_version }}"
      register: check_output
      failed_when: false

    - name: "Start service"
      ansible.builtin.service:
        name: postgresql-{{ pg_version }}
        state: started
      when: '"Active: inactive (dead)" in check_output.stdout'
    #  when: 'check_output.stdout is search("Active: inactive")'
