---
- name: Storage Auto-Detect
  hosts: test
  gather_facts: true
  become: true
  tasks:
    - name: Storage Auto-Detect
      ansible.builtin.import_role:
        name: storage_management
        tasks_from: storage_device_auto_detect
