---
- name: "Create new VM"
  hosts: hypervisor
  gather_facts: no
  tasks:
    - name: "Create New VM"
      ansible.builtin.import_role:
        name: host_hypervisor_management
        tasks_from: create_new_vm

- name: "Add the New VM to inventory"
  hosts: localhost
  gather_facts: no
  become: yes
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: "Add the New VM to inventory"
      ansible.builtin.import_role:
        name: host_hypervisor_management
        tasks_from: add_vm_to_inventory