---
- name: "Install, Initialize and Start PostgreSQL service"
  hosts: dbs
  become: yes
  vars_files:
    - ../group_vars/vault.yml
  vars:
    pg_version: 13
  roles:
    - postgresql_config_and_install

