name: Build pgBackRest
on: workflow_dispatch
jobs:
  run-build-process:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
    steps:
      - name: Create build directory
        run: |
          mkdir -p /build
      - name: Download version 2.58.0 of pgBackRest to /build path
        run: |
          dnf install -y wget
          wget -q -O - https://github.com/pgbackrest/pgbackrest/archive/release/2.58.0.tar.gz | tar zx -C /build

      - name: Config repos and install dependencies
        run: | 
          dnf install -y dnf-plugins-core
          dnf config-manager --set-enabled crb || dnf config-manager --set-enabled powertools
          dnf install -y epel-release
          dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
          dnf -qy module disable postgresql
          dnf install -y \
          meson \
          gcc \
          postgresql14-devel \
          openssl-devel \ 
          libxml2-devel \
          lz4-devel \ 
          libzstd-devel \
          bzip2-devel \
          libyaml-devel \
          libssh2-devel
      - name: Configure and Compile pgBackRest
        run: | 
          meson setup /build/pgbackrest /build/pgbackrest-release-2.58.0
          ninja -C /build/pgbackrest
      - name: Archive the pgBackRest build
        run: | 
          tar -czvf pgbackrest.tar.gz /build/pgbackrest/src/pgbackrest
      - name: Create GitHub Release for pgbackrest build
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pgbackrest.tar.gz
          tag_name: pgBackRest v2.58.0
          name: Release of 'pgBackRest' v2.58.0
          body: "My release of the pgBackRest build."

